# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: studio

steps:
  - task: AzureResourceManagerTemplateDeployment@3
    inputs:
      deploymentScope: 'Resource Group'
      azureResourceManagerConnection: 'BitFrozen Azure'
      subscriptionId: '4c367f27-b103-4970-90a6-321257fab178'
      action: 'Create Or Update Resource Group'
      resourceGroupName: 'rg-mslrn-pipes-eu'
      location: 'East US'
      templateLocation: 'URL of the file'
      csmFileLink: 'https://raw.githubusercontent.com/bitfrozen/az-204/main/arm-pipelines/azuredeploy.json'
      overrideParameters: '-projectName prj5581'
      deploymentMode: 'Incremental'
      deploymentName: 'DeployPipelineTemplate'
